* Log monitoring
** Dependencies

*** Linker
The linking takes most of the time during the development cycle. A faster linker would go a long way.

#+BEGIN_SRC
sudo yum install lld clang openssl-develop flatc libstdc++.so.6
#+END_SRC

Add the below linkers to the =.cargo/config.toml= file


#+BEGIN_SRC
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
#+END_SRC

*** development tools

Install cargo watch

#+BEGIN_SRC
cargo install cargo-watch
#+END_SRC


#+BEGIN_SRC
rustup component add rustfmt
#+END_SRC

#+BEGIN_SRC
rustup component add clippy
#+END_SRC

*** Wal block layout
+-------------------------------+
| WalBlockHeader (64 bytes)      |
+-------------------------------+
| FlatBuffers Metadata           |
| (starts at metadata_offset)    |
|  + FlatbufMeta root            |
|    + version (1 byte)          |
|    + flags (1 byte)            |
|    + timestamp (8 bytes)       |
|    + serialization (2 bytes)   |
|    + magic_number (8 bytes)    |
|    + meta (union)              |
|      + EventMeta / LogMeta / TraceMeta |
+-------------------------------+
| Reserved Area (optional)       |
+-------------------------------+
| Arrow IPC payload (data)       |
| (starts at data_offset)        |
+-------------------------------+

* Install the sqlx CLI for migrations

#+begin_src bash
cargo install --version=0.5.7 sqlx-cli --no-default-features --features postgres
#+end_src



// Points

1. Window 11:00 to 12:00
2. Record 1 = min - 10:55 && max - 11:20
3. Record 2 = min - 10:40 && max - 11:10
4. Record 3 =  min - 10:45 && max - 10:58
5. Record 4 = min - 10.45 && max - 12:05   --> massive window spanning 2 windows - this cannot be handled properly

And Record 1 in window 1 and window 2
And record 2 in window 1 and window 2
And record 3 in window 1

What should be the trigger times? 10:55 just 10 secs from the time of the record. Record 1 max time is 11:20 so the window technically closed.
But for this to work, i should stick to batches smaller then the size of the window.
