version: '3.8'

services:
  db:
    image: postgres:16-alpine # Or a specific version like postgres:13, postgres:14, postgres:15
    container_name: my_postgres_db # Optional: Give your container a specific name
    environment:
      POSTGRES_DB: mydatabase # The name of the database to create
      POSTGRES_USER: myuser # The username for the database
      POSTGRES_PASSWORD: mypassword # The password for the database user
      PGDATA: /var/lib/postgresql/data/pgdata # Optional: Specify the data directory within the container
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount a named volume for persistent data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: To run an initialization script
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    restart: unless-stopped # Always restart unless explicitly stopped

volumes:
  pgdata: # Define the named volume