name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Clang (no sudo)
        run: |
          apt update
          apt install -y clang
          apt install -y lld
          apt install -y cmake
          # apt install -y flatbuffers-compiler
          # Clone FlatBuffers repo
          rm -rf flatbuffers
          git clone https://github.com/google/flatbuffers.git
          cd flatbuffers
          git checkout v24.3.25

          # Build and install flatc
          cmake -G "Unix Makefiles"
          make -j$(nproc)
          sudo make install

          # Verify version
          flatc --version
          clang --version
        shell: bash

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose
